print("Hello World!")
print(" Hello World!")
print("H ello World!")
print("He llo World!")
print("Hel lo World!")
print("Hell o World!")
print("Hello  World!")
print("Hello W orld!")
print("Hello Wo rld!")
print("Hello Wor ld!")
print("Hello Worl d!")
print("Hello World !")
print("Hello World! ")
print("Hello World!")
