import time

print("Hello World!")
time.sleep(100)
print(" Hello World!")
time.sleep(100)
print("H ello World!")
time.sleep(100)
print("He llo World!")
time.sleep(100)
print("Hel lo World!")
time.sleep(100)
print("Hell o World!")
time.sleep(100)
print("Hello  World!")
time.sleep(100)
print("Hello W orld!")
time.sleep(100)
print("Hello Wo rld!")
time.sleep(100)
print("Hello Wor ld!")
time.sleep(100)
print("Hello Worl d!")
time.sleep(100)
print("Hello World !")
time.sleep(100)
print("Hello World! ")
time.sleep(100)
print("Hello World!")
